### ISSUE TITLE
fatal error 

### ISSUE THREAD

**Issue by D3MONSKYS** [LostString/UltraStaff#6]
Fatal error trying to convert UltraStaff v1.5.1-BETA:me/lost/ultrastaff/spigot/events/BlockBreak.class
org.bukkit.plugin.AuthorNagException: No legacy enum constant for DEEPSLATE_EMERALD_ORE. Did you forget to define a modern (1.13+) api-version in your plugin.yml?
        at org.bukkit.craftbukkit.util.Commodore$1$1.visitFieldInsn(Commodore.java:314) ~[paper-1.20.6.jar:1.20.6-117-716b868]
        at org.objectweb.asm.MethodVisitor.visitFieldInsn(MethodVisitor.java:403) ~[asm-9.7.jar:9.7]
        at org.objectweb.asm.commons.MethodRemapper.visitFieldInsn(MethodRemapper.java:145) ~[asm-commons-9.7.jar:9.7]
        at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2443) ~[asm-9.7.jar:9.7]
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1512) ~[asm-9.7.jar:9.7]
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:745) ~[asm-9.7.jar:9.7]
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:425) ~[asm-9.7.jar:9.7]
        at org.bukkit.craftbukkit.util.Commodore.convert(Commodore.java:169) ~[paper-1.20.6.jar:1.20.6-117-716b868]
        at org.bukkit.craftbukkit.util.CraftMagicNumbers.processClass(CraftMagicNumbers.java:413) ~[paper-1.20.6.jar:1.20.6-117-716b868]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:220) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at UltraStaff-1.5.1-BETA.jar/me.lost.ultrastaff.UltraStaff.registerEvents(UltraStaff.java:129) ~[UltraStaff-1.5.1-BETA.jar:?]
        at UltraStaff-1.5.1-BETA.jar/me.lost.ultrastaff.UltraStaff.onEnable(UltraStaff.java:59) ~[UltraStaff-1.5.1-BETA.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-117-716b868]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-117-716b868]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604) ~[paper-1.20.6.jar:1.20.6-117-716b868]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.6.jar:1.20.6-117-716b868]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-117-716b868]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-117-716b868]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-117-716b868]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-117-716b868]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-117-716b868]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by LostString** [comment]
I'm doing a **"recoding"** of the plugin to fix bugs and implement things, I'll upload the plugin update soon, thanks for letting me know!

**Comment by D3MONSKYS** [comment]
no problem, and thanks for doing it, if i had money id give u much love
